### ISSUE TITLE
Crash when rotating near the bottom

### ISSUE THREAD

**Issue by Trevor-Z** [xterminal86/gms2-tetris#1]
Hello. Thanks for making this project available, I've been testing it and reading the code to learn GML.

There seems to be a bug, if I try to rotate a figure near the bottom, so that in the new position a part of it will collide with the floor, the code crashes with this error:

___________________________________________
############################################################################################
ERROR in
action number 1
of Key Press Event for <Up> Key
for object objFigure:

ds_list_find_value argument 1 incorrect type (undefined) expecting a ds_list
 at gml_Script_scr_grid_get_value (line 6) -        return rowNum[| arrayY];
############################################################################################
gml_Script_scr_grid_get_value (line 6)
gml_Script_scr_can_be_placed (line 191) -              checks[2] = (scr_grid_get_value(figurePosY + 2, newX) == 0);
gml_Script_scr_can_move (line 66) -        return scr_can_be_placed(newPosX, hx);
gml_Object_objFigure_KeyPress_38 (line 6) - if (!scr_can_move(figurePosX))

Any idea how to fix it?

**Comment by xterminal86** [comment]
Hi.

Wow, it's been a while now, so I can't say from the top of my head - gotta look into the code. )
But when I created this project I also was just fiddling around with GMS, having no experience prior, so the quality of code isn't even average I'd say.
I'll see if I still have GMS installed on my PC and try to fix this.

**Comment by Trevor-Z** [comment]
I chose your implementation of Tetris because it's simple and straight to the point, and I've learned a lot from it already.

But not nearly enough to tackle this bug myself, haha.

**Comment by xterminal86** [comment]
I already forgot how awfully inconvenient it is to work inside GMS itself. XD

Anyway, I think I managed to fix the bug, so I updated the release archive.
